name: Guess my Number - Check code quality
on:
  push:

jobs:
  format-code:
    runs-on: ubuntu-latest

    env:
      source-directory: lib/guess_my_number

    steps:
      - name: Get code
        uses: actions/checkout@v2
      - name: Install flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.0'
      - name: Setup project
        run: |
        cd ${{env.source-directory}}
        flutter pub get
      - name: Format code
        run: |
        cd ${{env.source-directory}}
        flutter format -l 120 --set-exit-if-changed .
  analyze-code:
    runs-on: ubuntu-latest

    env:
      source-directory: lib/guess_my_number

    steps:
      - name: Get code
        uses: actions/checkout@v2
      - name: Install Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '2.2.0'
      - name: Setup project
        working-directory: ${{env.source-directory}}
        run: |
        cd ${{env.source-directory}}
        flutter pub get

      - name: Analyze code
        working-directory: ${{env.source-directory}}
        run:|
        cd ${{env.source-directory}}
        flutter analyze
